// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YummyAnimeNotifier.Infrastructure.Persistence;

#nullable disable

namespace YummyAnimeNotifier.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(YummyAnimeDbContext))]
    [Migration("20260627160832_AnimeTranslationVersionMigration")]
    partial class AnimeTranslationVersionMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbAnime", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleasedEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceLink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("SourceLink")
                        .IsUnique();

                    b.ToTable("Anime", (string)null);
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbAnimeTranslation", b =>
                {
                    b.Property<Guid>("AnimeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranslationSourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleasedEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("AnimeId", "TranslationSourceId");

                    b.HasIndex("TranslationSourceId");

                    b.ToTable("AnimeTranslation", (string)null);
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnimeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TotalEpisodes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TranslationSourceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessage", (string)null);
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TranslationSourceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TranslationSourceId");

                    b.HasIndex("AnimeId", "TranslationSourceId", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("Release", (string)null);
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TranslationSourceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.HasIndex("TranslationSourceId");

                    b.HasIndex("UserId", "AnimeId", "TranslationSourceId")
                        .IsUnique();

                    b.ToTable("Subscription", (string)null);
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbTranslationSource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Type", "Name")
                        .IsUnique();

                    b.ToTable("TranslationSource", (string)null);
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbAnimeTranslation", b =>
                {
                    b.HasOne("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbAnime", "Anime")
                        .WithMany("AnimeTranslations")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbTranslationSource", "TranslationSource")
                        .WithMany("AnimeTranslations")
                        .HasForeignKey("TranslationSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("TranslationSource");
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbNotification", b =>
                {
                    b.HasOne("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbRelease", "Release")
                        .WithMany("Notifications")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbRelease", b =>
                {
                    b.HasOne("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbAnime", "Anime")
                        .WithMany("Releases")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbTranslationSource", "TranslationSource")
                        .WithMany("Releases")
                        .HasForeignKey("TranslationSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("TranslationSource");
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbSubscription", b =>
                {
                    b.HasOne("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbAnime", "Anime")
                        .WithMany("Subscriptions")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbTranslationSource", "TranslationSource")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TranslationSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbUser", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("TranslationSource");

                    b.Navigation("User");
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbAnime", b =>
                {
                    b.Navigation("AnimeTranslations");

                    b.Navigation("Releases");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbRelease", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbTranslationSource", b =>
                {
                    b.Navigation("AnimeTranslations");

                    b.Navigation("Releases");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("YummyAnimeNotifier.Infrastructure.Persistence.Entities.DbUser", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
